# Generated by Django 5.0.7 on 2024-08-03 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'Barra'), ('2', 'Haltere'), ('3', 'Kettlebell'), ('4', 'Máquina'), ('5', 'Polia'), ('6', 'Peso Corporal'), ('7', 'Banco')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Musculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'Quadríceps'), ('2', 'Posterior'), ('3', 'Glúteos'), ('4', 'Panturrilha'), ('5', 'Bíceps'), ('6', 'Tríceps'), ('7', 'Peito'), ('8', 'Costas'), ('9', 'Ombros'), ('10', 'Abdômen')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField()),
                ('gif_url', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.categoria')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.equipamento')),
            ],
        ),
        migrations.CreateModel(
            name='MusculoExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercicio', models.ManyToManyField(related_name='musculos', to='workouts.exercicio')),
                ('musculo', models.ManyToManyField(related_name='exercicios', to='workouts.musculo')),
            ],
        ),
    ]
