# Generated by Django 5.0.7 on 2024-08-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_remove_exercicio_category_delete_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='musculo',
            field=models.ManyToManyField(related_name='musculos', to='workouts.musculo'),
        ),
        migrations.DeleteModel(
            name='MusculoExercicio',
        ),
    ]
